### ISSUE TITLE
The Phase 1Assignment Not Available

### ISSUE THREAD

**Issue by sokogfb** [BongoHive/front-end-learning-resources#1]
The  Phase 1 Assignment is not available

![Capture Issue](https://user-images.githubusercontent.com/32112696/59215902-bd712e80-8bba-11e9-8a73-683995c411c0.PNG)

**Comment by Joebbrien** [comment]
Hi @SOXCODE  thanks for raising this issue
try accessing the link again it should be working

Thanks

**Comment by alfeyo** [comment]
Hello, @SOXCODE have reached our limit on GitHub, but working on providing access to more people.
We still have not received any response from GitHub.
